name: Deploy to Databricks via YAML

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get Databricks Token from Key Vault
      id: kv
      run: |
        token=$(az keyvault secret show --name ADB-TOKEN --vault-name adb-kv-dev --query value -o tsv)
        echo "::add-mask::$token"
        echo "DATABRICKS_TOKEN=$token" >> $GITHUB_ENV
        echo "DATABRICKS_HOST=https://adb-113488527594700.0.azuredatabricks.net" >> $GITHUB_ENV

    - name: Install Databricks CLI (v0.205+)
      run: |
        pip install databricks
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Deploy asset bundle
      env:
        DATABRICKS_TOKEN: ${{ env.DATABRICKS_TOKEN }}
        DATABRICKS_HOST: ${{ env.DATABRICKS_HOST }}
      run: |
        which databricks
        databricks bundle validate
        databricks bundle deploy

