name: Deploy to Databricks via Asset Bundle

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: https://adb-113488527594700.0.azuredatabricks.net

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get Databricks Token from Key Vault
      id: kv
      run: |
        token=$(az keyvault secret show --name ADB-TOKEN --vault-name adb-kv-dev --query value -o tsv)
        echo "::add-mask::$token"
        echo "DATABRICKS_TOKEN=$token" >> $GITHUB_ENV

    - name: Install Databricks CLI (v0.200+)
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | bash
        echo "$HOME/.databricks/bin" >> $GITHUB_PATH

    - name: Deploy asset bundle
      env:
        DATABRICKS_TOKEN: ${{ env.DATABRICKS_TOKEN }}
        DATABRICKS_HOST: ${{ env.DATABRICKS_HOST }}
      run: |
        databricks bundle validate
        databricks bundle deploy
